Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.ListProjectsFunction
      CodeUri: C:\Users\Alumno_FP\IdeaProjects\AWSPrueba\HelloWorldFunction
      Runtime: java17
      Architectures:
        - x86_64